services:
  mongodb:
    image: mongo:6
    container_name: scheduler_db
    restart: unless-stopped
    ports:
      - '27017'
    volumes:
      - scheduler_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}

  node-app:
    build:
      context: .
    container_name: scheduler-node-app
    restart: unless-stopped
    ports:
      - '127.0.0.1:${PORT}:3000'
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ./uploads:/app/uploads
    command: ['node', 'dist/app.js']
    working_dir: /app

volumes:
  scheduler_db_data:
